carcollector/urls.py
from django.contrib import admin
from django.urls import path, include


from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('cars/', views.cars_index, name='index'),
  path('cars/<int:car_id>/', views.cars_detail, name='detail'),
  path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
  path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
  path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
  path('cars/<int:car_id>/add_fueling/', views.add_fueling, name='add_fueling'),
    # associate a driver with a car (M:M)
  path('cars/<int:car_id>/assoc_driver/<int:driver_id>/', views.assoc_driver, name='assoc_driver'),
  # unassociate a driver and car
  path('cars/<int:car_id>/unassoc_driver/<int:driver_id>/', views.unassoc_driver, name='unassoc_driver'),
  path('drivers/', views.DriverList.as_view(), name='drivers_index'),
  path('drivers/<int:pk>/', views.DriverDetail.as_view(), name='drivers_detail'),
  path('drivers/create/', views.DriverCreate.as_view(), name='drivers_create'),
  path('drivers/<int:pk>/update/', views.DriverUpdate.as_view(), name='drivers_update'),
  path('drivers/<int:pk>/delete/', views.DriverDelete.as_view(), name='drivers_delete'),
  # path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# A tuple of 2-tuples
GALLONS = (
    ('1', '1 Gallons'),
    ('5', '5 Gallons'),
    ('F', 'Fill it up!')
)

class Driver(models.Model):
  name = models.CharField(max_length=50)
  skill = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('drivers_detail', kwargs={'pk': self.id})

# Create your models here.

class Car(models.Model):
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    year = models.IntegerField()
    drivers = models.ManyToManyField(Driver)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.make

    def get_absolute_url(self):
        return reverse('detail', kwargs={'car_id': self.id})


class Fueling(models.Model):
  date = models.DateField('fueling date')
  gallons = models.CharField(
    max_length=1,
	choices=GALLONS,
	default=GALLONS[0][0]
  )
  # Create a car_id FK
  car = models.ForeignKey(Car, on_delete=models.CASCADE)
  
  def __str__(self):
        return f"{self.get_gallons_display()} on {self.date}"
    
  class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Fueling

class FuelingForm(ModelForm):
  class Meta:
    model = Fueling
    fields = ['date', 'gallons']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Car, Driver
from .forms import FuelingForm







class CarCreate(CreateView):
  model = Car
  fields = ['make', 'description', 'year']
  success_url = '/cars/'

class CarUpdate(UpdateView):
  model = Car
  # Let's disallow the renaming of a car by excluding the name field!
  fields = ['make', 'description', 'year']

class CarDelete(DeleteView):
  model = Car
  success_url = '/cars/'


# Define the home view
def home(request):
  return HttpResponse('<h1>Hello /0ᐠ|||ᐟ0\</h1>')

def about(request):
  return render(request, 'about.html')

# def cars_index(request):
#   return render(request, 'cars/index.html', { 'cars': cars })

def cars_index(request):
  cars = Car.objects.all()
  return render(request, 'cars/index.html', { 'cars': cars })

def cars_detail(request, car_id):
  car = Car.objects.get(id=car_id)
  # Get the drivers the car doesn't have
  drivers_car_doesnt_have = Driver.objects.exclude(id__in = car.drivers.all().values_list('id'))
  # instantiate FuelingForm to be rendered in the template
  fueling_form = FuelingForm()
  return render(request, 'cars/detail.html', {
    # include the car and fueling_form in the context
    'car': car, 'fueling_form': fueling_form,
    # Add the drivers to be displayed
    'drivers': drivers_car_doesnt_have
  })

def add_fueling(request, car_id):
  # create a ModelForm instance using the data in request.POST
  form = FuelingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the car_id assigned
    new_fueling = form.save(commit=False)
    new_fueling.car_id = car_id
    new_fueling.save()
  return redirect('detail', car_id=car_id)

def assoc_driver(request, car_id, driver_id):
  print(car_id, driver_id)
  Car.objects.get(id=car_id).drivers.add(driver_id)
  return redirect('detail', car_id=car_id)

def unassoc_driver(request, car_id, driver_id):
  Car.objects.get(id=car_id).drivers.remove(driver_id)
  return redirect('detail', car_id=car_id)

class DriverList(ListView):
  model = Driver

class DriverDetail(DetailView):
  model = Driver

class DriverCreate(CreateView):
  model = Driver
  fields = '__all__'

class DriverUpdate(UpdateView):
  model = Driver
  fields = ['name', 'skill']

class DriverDelete(DeleteView):
  model = Driver
  success_url = '/drivers/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Car Collector</h1>
<hr />
<p>Hire the Car Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Car Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CarCollector</a></li>
        </ul>
        <ul class="right">
          <!-- <li><a href="/about">About</a></li> -->
          <!-- <li><a href="/cars">View All My Cars</a></li> -->
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'drivers_create' %}">Add a Driver</a></li>
          <li><a href="{% url 'drivers_index' %}">View All Drivers</a></li>
          <li><a href="{% url 'cars_create' %}">Add a Car</a></li>
          <li><a href="{% url 'index' %}">View All My Cars</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Car Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Car Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ car.make }}</span>
        <p>Model: {{ car.model }}</p>
        <p>Description: {{ car.description }}</p>
        {% if car.age > 0 %}
          <p>Year: {{ car.year }}</p>
        {% else %}
          <p>Year: Used</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cars_update' car.id %}">Edit</a>
        <a href="{% url 'cars_delete' car.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_fueling' car.id %}" method="post">

        {% csrf_token %}
        {{ fueling_form.as_p }}
        <input type="submit" class="btn" value="Add Fueling">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Gas</th></tr>
      </thead>
      <tbody>
        {% for fueling in car.fueling_set.all %}
          <tr>
            <td>{{fueling.date}}</td>
            <td>{{fueling.get_gallons_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <hr>
<div class="row">
  <div class="col s6">
    <h3>{{ car.model }}'s Drivers</h3>
    {% if car.drivers.count %}
      {% for driver in car.drivers.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              The <span style="skill: {{ driver.skill }}">{{ driver.skill }}</span> {{ driver.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Drivers :(</h5>
    {% endif %}
  </div>
  <!-- Available drivers will come after this line -->
  <div class="col s6">
    <h3>Available Drivers</h3>
    {% if drivers.count %}
      {% for driver in drivers.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              The <span style="skill: {{ driver.skill }}">{{ driver.skill }}</span> {{ driver.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_driver' car.id driver.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{car.name}} Already Has All Drivers Available</h5>
    {% endif %}
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  var selectEl = document.getElementById('id_gallons');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Car List</h1>

{% for car in cars %}
  <div class="card">
    <a href="{% url 'detail' car.id %}">
      <div class="card-content">
        <span class="card-title">{{ car.name }}</span>
        <p>make: {{ car.make }}</p>
        <p>Description: {{ car.description }}</p>
        {% if car.year > 0 %}
          <p>Year: {{ car.year }}</p>
        {% else %}
          <p>Year: New</p>
        {% endif %}
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete this car? <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' car.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/driver_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Driver</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'drivers_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/driver_detail.html
{% extends 'base.html' %}
{% block content %}

<h1> Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ driver.name }}</span>
        <p>Skill: {{ driver.skill }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'drivers_update' driver.id %}">Edit</a>
        <a href="{% url 'drivers_delete' driver.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/driver_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Driver</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/driver_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Driver List</h1>

{% for driver in driver_list %}
  <a href="{% url 'drivers_detail' driver.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ driver.name }}</span>
            <p>Skill: {{ driver.skill }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}